[global]
mraauthor=["jotego"]

[features]
beta = true
# debug = true

[parse]
sourcefile="vigilant.cpp"
skip = { bootlegs=true, setnames = [ "kikcubic", "kikcubicb", "buccanrs", "buccanrsa", "buccanrsb" ] }

[buttons]
core=$JTFRAME_BUTTONS
Names = [ { names="Punch, Kick "} ]

[rbf]
name="jtvigil"

[dipsw]
bitcnt = 16
delete = [ "Unused", "Unknown" ]

[ROM]
regions = [
    { name="maincpu", No_offset=true   },
    { name="soundcpu", start=$BA1_START },
    { name="m72",      start=$PCM_START },

    { name="gfx1", start=$BA2_START, width=16, No_offset=true },
    { name="gfx2", start=$GFX2_START, width=16, No_offset=true },
    { name="gfx3",     start=$BA3_START, No_offset=true },
    { name="plds", skip=true },
    { name="proms", skip=true }
]

order = [
    "maincpu", "soundcpu", "m72",
    "gfx1", "gfx2", "gfx3"
]
